### ISSUE TITLE
Feature: support round trip

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [sparsetech/toml-scala#1]
please consider support for round trip codec:
i.e. `toml` -> `code` -> `toml` with high fidelity, including comments

**Comment by tindzk** [comment]
Sorry, I did not get a notification for your issue.

Could you please elaborate? As I understand, the idea is to generate TOML from the AST representation?

**Comment by tindzk** [comment]
For the time being, I opted for a simple implementation based on the current AST. Comments are therefore not supported yet. We could explore this as part of a separate issue.

**Comment by joprice** [comment]
Including comments would be handy for tooling that modifies a config in place, retaining any user-generated comments, and adding machine-generated ones.
