### ISSUE TITLE
Can't parse float number expressed in scientific notation

### ISSUE THREAD

**Issue by SnipyJulmy** [sparsetech/toml-scala#11]
Toml-scala can't parse number in floating point expressed in a scientific notation.

Example :
```scala
scala> import toml.Toml ; Toml.parse("poly = -45e12")
import toml.Toml
res4: Either[String,toml.Value.Tbl] = Right(Tbl(Map(poly -> Real(-4.5E13))))

scala> import toml.Toml ; Toml.parse("poly = -45.321e12")
import toml.Toml
res5: Either[String,toml.Value.Tbl] = Left(End:1:15 ..."e12")
```
Let me know if you need more from me.

**Comment by tindzk** [comment]
Thanks for the bug report! We should also make sure that all other [floating point examples](https://github.com/toml-lang/toml#float) from the TOML specification work as expected.
