### ISSUE TITLE
How best to handle key case differences?

### ISSUE THREAD

**Issue by Synesso** [sparsetech/toml-scala#9]
I want to parse
```
BANANA_SMOOTHIE="please, yes"
HEDGEHOGS="always"
``` 
into `case class Order(bananaSmoothie: String, hedgehogs: String)` using a `Codec`.

Without any special handling, this fails due to the case differences for the keys.

I could define `case class Order(BANANA_SMOOTHIE: String, HEDGEHOGS: String)`, but I'd rather not. 

For now I'm using raw parsing, with no Codec. Is it possible to accommodate for different key cases?

**Comment by tindzk** [comment]
You could define a function like [Embed.root()](https://github.com/sparsetech/toml-scala/blob/master/shared/src/main/scala/toml/Embed.scala#L46-L55) that iterates over the AST and changes all keys. Then, you can call `Codec`'s `apply()` function to get your `case class` representation:

```scala
def toCamelCase: Value.Tbl => Value.Tbl = ???
def parseCustomToml[A](toml: String)(implicit codec: Codec[A]): Either[Codec.Error, A] =
  Toml.parse(toml).left.map((List(), _)).right.map(toCamelCase).flatMap(codec(_, Map(), 0))
```

**Comment by tindzk** [comment]
@Synesso Did it resolve your issue?

**Comment by Synesso** [comment]
It seems reasonable, but I decided in the end to extract the values manually from `Tbl.values`. Feel free to close, or keep open if you intend to build something into the lib. And thanks for your help.

**Comment by tindzk** [comment]
Thanks. I am not sure how common the use case is, so I will close the issue for now. If there is more demand from users to map keys (or even values), I'd be happy to revisit it in the future.
